linters-settings:
  wsl:
    # Allow declarations (var) to be cuddled.
    allow-cuddle-declarations: true

linters:
  enable-all: true
  disable:
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - gofumpt
    - gomoddirectives
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - ifshort
    - interfacebloat
    - ireturn
    - lll
    - nonamedreturns
    - nosnakecase
    - testpackage
    - varnamelen
    # deprecated
    - deadcode
    - golint
    - interfacer
    - maligned
    - scopelint
    - structcheck
    - varcheck
    # TODO: fix and remove
    - thelper
    - wrapcheck

issues:
  exclude-rules:
    # some linters in tests files
    - path: _test\.go
      linters:
        - dogsled
        - dupl
        - errcheck
        - forcetypeassert
        - gocyclo
        - goerr113
    # file and dir permissions can be read by more or we would use umask
    - text: "permissions to be 0[0-9]{3} or less"
      linters:
        - gosec
    # magic number from persistent flags
    - source: "(pflags\\.|PersistentFlags\\(\\)\\.)"
      linters:
        - gomnd
    # magic number from cobra args definition
    - source: "Args: +cobra\\."
      linters:
        - gomnd
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8
    - text: "does not use range value in test Run"
      linters:
        - paralleltest
    # Tests in cli cannot be run parallel as of now
    - path: cli
      linters:
        - paralleltest
    # Use a lot of base 10 conversions
    - text: "Magic number: 10"
      linters:
        - gomnd
    # And 32/64 bit sizes
    - text: "Magic number: 32"
      linters:
        - gomnd
    - text: "Magic number: 64"
      linters:
        - gomnd
    - text: "should be written without leading space as `//nolint:"
      linters:
        - nolintlint
