#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
        deb-systemd-invoke stop lxe.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/lxe" ] || [ -e "/etc/init/lxe.conf" ]; then
        invoke-rc.d lxe stop || exit $?
fi
# End automatically added section
