.\" Manpage for lxe.
.TH man 8 "21 Oct 2018" "1.0" "lxe man page"
.SH NAME
lxe \- a shim of the Kubernetes CRI for LXD
.SH SYNOPSIS
lxe [\-h | \-\-help]
.SH DESCRIPTION
This is a minimal manpage, see lxe \-\-help for usage.
.SH OPTIONS
All command line options may be set using the configuration file, the descriptions indicate the configuration option to set\&.
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show a short usage summary\&.
.SH AUTHOR
Automatic Server AG (info@automatic\-server.com)
