name: build

on:
  push:
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Download dependencies
        run: |
          make dep-go
      - name: Build
        run: |
          make build-go
      - name: Test
        run: |
          make test-go-unit
          make test-go-race
      - name: Lint
        run: |
          make lint-go
      - name: Generate
        run: |
          make generate-go
      - name: Untracked files or diffs
        run: |
          go mod tidy
          git diff
          git diff-index HEAD --
          git diff-index --quiet HEAD --
