name: ci

on:
  pull_request:
    branches:
      - master
      - workflow
      - releases/*
  push:
    branches:
      - master
      - workflow
      - releases/*

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GO111MODULE: on
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.x
    # - name: load dependencies
    #   run: |
    #     go mod download
    #     go mod verify
    - name: build
      run: make build

  test:
    runs-on: ubuntu-18.04
    env:
      GO111MODULE: on
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.x
    # - name: load dependencies
    #   run: |
    #     go mod download
    #     go mod verify
    - name: test
      run: make test

  lint:
    runs-on: ubuntu-18.04
    env:
      GO111MODULE: on
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.x
    # - name: load dependencies
    #   run: |
    #     go mod download
    #     go mod verify
    - name: test
      run: make lint
