name: test

on:
  pull_request:
    branches:
      - master
      - workflow
      - releases/*
  push:
    branches:
      - master
      - workflow
      - releases/*

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup go
      uses: actions/setup-go@master
    - name: load dependencies
      run: |
        go mod download
        go mod verify
    - name: test
      run: make test
